variable "DBUSER" {}
variable "DBPASS" {}
variable "VPC_ID" {}
variable "PRIVATE_SUBNETS" {}
variable "PUBLIC_SUBNETS" {}
variable "MGMT_VPC_ID" {}
variable "TAGS" {}
variable "INSTANCE_TYPE" {}
variable "PROD" {}
variable "NONPROD" {}
variable "GITLAB_USER" {}
variable "GITLAB_PASSWORD" {}
